### ISSUE TITLE
Emergency: CANNOT fetch ISS TLE data.

### ISSUE THREAD

**Issue by lbwei1016** [DENGRENHAO/Nasa_Space_App#2]
## How this problem happens?
Our project fetch **ISS TLE data** from [live.ariss.org/iss.txt](http://live.ariss.org/iss.txt). However, the TLS certificate of this site has expired a few weeks ago, and we discoverd this problem last week. Since we didn't expect the certificate is to expire in such near future, we didn't handle such exception, resulting in our ISS tracker cannot function properly (see Pic. 1).

> Pic. 1
![issum](https://user-images.githubusercontent.com/64310812/203243307-4ad72d0f-6679-4b2c-aa64-cbb76518b453.png)

---

## What have we done?
After discovering this problem, we immediately sent an email to the site administrator(carol.jackson@ariss-usa.org) of [ariss.org](https://www.ariss.org/) (see Pic. 2). However we didn't receive any response for over five days, so we turned to the [facebook page of ARISS](https://www.facebook.com/profile.php?id=100057685208684) (see Pic. 3). Luckily, this time we got a response quite soon (see Pic. 4).

> Pic. 2
![email](https://user-images.githubusercontent.com/64310812/203248238-724f3dca-c432-4a57-9cb9-a776f0a3b20d.png)

> Pic. 3
![fb](https://user-images.githubusercontent.com/64310812/203248299-a79606f4-fce3-436f-b54f-fc0d4652be4d.png)

> Pic. 4
![fb2](https://user-images.githubusercontent.com/64310812/203248339-25283ac2-7f08-4d79-bfea-f01ca44606a5.png)

---

## What will we do?

Since we are **now** competing in **NASA Space Apps Challenge** for **Global Awards**, we must ensure that our project can function normally during the judgments. Hence, apart from waiting for the site administrator to renew the certificate, we will commit some trivial patches **ONLY** to fix the problem mentioned here.

> This *issue* serves as a record to the problem we have encountered, and also how we try to solve it.

**Comment by SiriusKoan** [comment]
The reason of this problem is expired certificate, which means it can be solved by renewing the certificate (by site admin) or skip the certificate (by ourselves).
Since the site admin did not give us quick response, so we decided to solve the problem in the second way.
We have an VM for hosting the data from http://live.ariss.org/iss.txt, and use `curl` and crontab to write the data to a file every minute.
Finally, we use nginx to host the website, it will serve on port 8080 with HTTPS and return the content of the file.
In this way, our server is just a proxy for data transferring and allows us to use the data from an insecure website.
